# Generated by Django 5.1.7 on 2025-04-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_profile_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
    ]
